# Generated by Django 5.0.6 on 2024-07-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_usuario_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
