# Generated by Django 5.0.6 on 2024-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
